version: 2.1

orbs:
  ggshield: gitguardian/ggshield@volatile
  orb-tools: circleci/orb-tools@volatile


workflows:
  main:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - ggshield/scan:
          name: ggshield-scan # best practice is to name each orb job
          base_revision: <<pipeline.git.base_revision>>
          revision: <<pipeline.git.revision>>
