---

version: 2.1

description: >
  Easily integrate GitGuardian shield into your CircleCI projects.
  Scan your commits for secrets and other policy breaks

display:
  source_url: https://github.com/GitGuardian/gg-shield-orb
  home_url: https://dashboard.gitguardian.com/

examples:
  scan:
    description: |
      Scan commits when they land on VCS. Do not forget to add an environment
      variable GITGUARDIAN_API_KEY with your API Key in the project settings
    usage:
      version: 2.1
      orbs:
        # This version number refers to the version of the orb
        ggshield: gitguardian/ggshield@x.y
      workflows:
        scan_my_commits:
          jobs:
            - ggshield/scan:
                name: ggshield-scan  # best practice is to name each orb job
                base_revision: <<pipeline.git.base_revision>>
                revision: <<pipeline.git.revision>>


jobs:
  scan:
    parameters:
      base_revision:
        description: |
          ID of the first commit to scan. Leave empty to only scan the latest
          commit.
        type: string
        default: ""
      revision:
        description: ID of the last commit to scan.
        type: string
      tag:
        description: |
          Pick a specific gitguardian/ggshield image variant:
          https://hub.docker.com/r/gitguardian/ggshield/tags
        default: latest
        type: string
    docker:
      - image: gitguardian/ggshield::<<parameters.tag>>
    environment:
      CIRCLE_RANGE: <<parameters.base_revision>>...<<parameters.revision>>
    steps:
      - checkout
      - run: ggshield scan -v ci
